# CommandManagerExtension config

title: "CommandManagerExtension"
description: "Select a plugin to run a command from."

main-page-buttons:
  - name: test
    description: test
    image-url: https://i.imgur.com/0Q4XQ4M.png
    commands:
      - name: testcommand
        command: say test worked
        image-url: https://i.imgur.com/0Q4XQ4M.png
  - name: test2
    description: test2
    image-url: https://i.imgur.com/0Q4XQ4M.png
    commands:
      - name: testcommand2
        command: say test worked2
        image-url: https://i.imgur.com/0Q4XQ4M.png

show-emotes: true

emote-list:
  - 6d9f24c0-6246-4c92-8169-4648d1981cbb
  - 7cec98d8-55cc-44fe-b0ae-2672b0b2bd37
  - 42fde774-37d4-4422-b374-89ff13a6535a